# Generated by Django 3.2.21 on 2023-09-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xsrconfiguration',
            name='source_file',
            field=models.FileField(blank=True, help_text='Upload the excel source file', null=True, upload_to=''),
        ),
    ]
