# Generated by Django 3.2.21 on 2023-09-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_xsrconfiguration_source_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xsrconfiguration',
            name='source_file',
            field=models.FileField(blank=True, help_text='Upload the excel source file', null=True, upload_to='source/'),
        ),
    ]
